### ISSUE TITLE
comment with "rem"

### ISSUE THREAD

**Issue by Danieleeee** [zabel-xyz/plsql-language#12]
Bug still in 1.0.0 
ref #10

**Comment by zabel-xyz** [comment]
it works for me...in version 1.0.0

![image](https://cloud.githubusercontent.com/assets/16486407/25288383/810201ba-26c5-11e7-9b71-3403c6f1f656.png)

Are you sure that version 1.0.0. is correctly installed ?
Check your folder \\.vscode\extensions
The version 1.0.0 is only installed when the vscode version is 1.11.0 otherwise it's the previous version (0.0.14 with the bug). I had this problem on a computer...

Check your file plsql.tmLanguage, I changed the regexp to fix this issue:
```
            <key>match</key>
            <string>\b(?i)rem(?:$|\s.*$)</string>
            <key>name</key>
            <string>comment.line.sqlplus.oracle</string>
```

**Comment by Danieleeee** [comment]
Insert space after _"rem"_, like _"rem hello world"_

**Comment by zabel-xyz** [comment]
![image](https://cloud.githubusercontent.com/assets/16486407/25291792/c5e7eb1a-26d3-11e7-8911-4208970dacde.png)

I don't understand what you want...
rem hello_world => comment (rem is used to mark comments in sqlplus)
remhello_world => not a comment

**Comment by Danieleeee** [comment]
We are in a package, no sqlplus command.
Look at this example:
[img] http://i.imgur.com/vPXP1Mf.jpg [/img]

**Comment by zabel-xyz** [comment]
If you are in a package, you'll not use the keyword "rem", so no problem in this case
If you aren't in a package it could be useful to colorize sqlplus comment.  
(the purpose of this extension is not only for packages) 

For me it's not a bug.

**Comment by Danieleeee** [comment]
I do not understand why you're altering.
I'm just pointing out that using "rem" to comment code can be counterproductive in **pl-sql language**.
If you want to do single line comments you can use **"--"** .
I do not know programmers who use 'rem' for comments.
All major software like **Toad, PL/SQL Developer, Oracle SQL Developer**, don't use 'rem' in their editor.
However you can do as you like, the extension is yours and you control it.

Thanks for the interest.
