### ISSUE TITLE
Document generation not always working

### ISSUE THREAD

**Issue by Pigna145** [zabel-xyz/plsql-language#13]
Seems as document generation is not working in all cases.

Don't see the snippet (on empty line) for this below:

```
   PROCEDURE store_content( i_snapshot     IN dummytable.snapshot%TYPE
                          , i_sample       IN INTEGER
                          , i_sample_time  IN TIMESTAMP
                          , i_ind_snapshot IN BOOLEAN
                          )
   AS
      l_dummy VARCHAR2(1);
   begin
     select * INTO l_dummy from dual;
   end;

```

But is does show for procedure below:

 ```
  PROCEDURE store_content( i_snapshot IN dummytable.snapshot%TYPE )
   AS

   begin
     select * from dual;

   end;

```

**Comment by zabel-xyz** [comment]
Your are right. It doesn't work. I'll see why...

**Comment by zabel-xyz** [comment]
fix in version 1.0.1

**Comment by Danieleeee** [comment]
Hi,
I'm trying to use this snippet:
` "pllastUpdate": {
        "prefix": "__last",
        "body": [
            "${PLDOC_AUTHOR} ${PLDOC_DATE}"
        ],
        "description": "Author and date"
    }`
It's in the default plsql.json snippets file, where are others snippets that works.
The problem is that it don't recognize variable **${PLDOC_AUTHOR}** and **${PLDOC_DATE}**.
Where I'm wrong?

Other question, where I find the folder of this extension? 
I'm looking into _Microsoft VS Code\resources\app\extensions_ but I do not find it.
Thanks

**Comment by zabel-xyz** [comment]
To use special variables like ${PLDOC_AUTHOR} or ${PLDOC_DATE}..., you can't use the default plsql.json.
You must use a special file **pldoc.json** and specify the folder in settings **plsql-language.pldoc.path**

(I must improve my documentation...)

**Comment by zabel-xyz** [comment]
The installed extensions are in folder <user>\.vscode\extensions

**Comment by Danieleeee** [comment]
Thanks.
Great job with new global variable like ${PLDOC_DATE}.
